---


- name: install python dependencies
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-pip
    - python-tk

    - python3-dev
    - python3-tk
    - python3-pip

    # required when compiling python from source
    - libsqlite3-dev
    - libbz2-dev


- name: setup pypirc
  file:
    state: link
    src: '{{ home }}/Dropbox/tech/pypirc'
    dest: '{{ home }}/.pypirc'



- name: install pillow dependencies
  apt: name={{ item }} state=present
  with_items:
    - libjpeg8-dev
    - libjpeg-dev
  become_user: root


- name: create virtualenv and install requirements
  pip:
    requirements: "{{ config_dir }}/ubuntu/config/requirements.txt"
    virtualenv: "{{ venv_dir }}/py36"
    virtualenv_python: python3.6
  # become_user: '{{ user }}'


# - name: install global python packages
#   command: pip install -r "{{ ubuntu_config }}/global-requirements.txt"


- name: create default ipython profile
  command: "{{ venv_bin}}/ipython profile create"


- name: install pyenv
  include: script_install.yml package="{{ item }}"
  with_items:
    - {name: 'pyenv', url: 'https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer'}
