---

- name: install desktop packages
  apt: name={{ item }} state=present
  with_items:
    - vlc
    - calibre
    - clementine
    - clipit
    - workrave
    - google-chrome-stable


# - name: disable chrome restore
#   lineinfile:
#     dest: "{{ home }}/.config/google-chrome/Default/preferences"
#     regexp: "^exited_cleanly"
#     line: "exited_cleanly: true"
