---

- name: install linux utilities
  apt: name={{ item }} state=present
  with_items:
    - apache2-utils
    - arpon
    - autoconf
    - automake
    - aptitude
    - build-essential
    - cowsay
    - dconf-tools
    - git
    - htop
    - iotop
    - nethogs
    - nmap
    - pastebinit
    - tree
    - unzip
    - vim
    - xcape
    - network-manager
    - ffmpeg
    - fonts-telu
    - tesseract-ocr
    - libbluetooth-dev
    - calibre


- name: install server packages
  apt: name={{ item }} state=present
  with_items:
    - rabbitmq-server
    - redis-server
    - openssh-server


- name: clone zsh-autosuggestions
  git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: ~/.zsh-autosuggestions
    version: master
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa


- name: clone zsh-syntax-highlighting
  git:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh-syntax-highlighting
    version: master
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa


- name: clone zsh-history-substring-search
  git:
    repo: git@github.com:zsh-users/zsh-history-substring-search.git
    dest: ~/.zsh-history-substring-search
    version: master
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa


- name: clone zaw
  git:
    repo: git@github.com:zsh-users/zaw.git
    dest: ~/.zaw
    version: master
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa
