---

- name: install linux utilities
  apt: name={{ item }} state=present
  with_items:
    - apache2-utils
    - arpon
    - autoconf
    - automake
    - aptitude
    - build-essential
    - cowsay
    - dconf-tools
    - git
    - htop
    - iotop
    - nethogs
    - nmap
    - pastebinit
    - tree
    - unzip
    - vim
    - xcape
    - network-manager
    - ffmpeg
    - fonts-telu
    - tesseract-ocr


- name: install server packages
  apt: name={{ item }} state=present
  with_items:
    - rabbitmq-server
    - redis-server
    - openssh-server
