- name: check if '{{ package.name }}' is installed
  stat: path='{{ config_bin }}/{{ package.name }}'
  register: binary


- name: download binary
  get_url:
    url='{{ package.url }}'
    dest='{{ config_bin }}/{{ package.name }}'
    mode=0777
  when:
    binary.stat.exists == False
  become_user: '{{ user }}'
